TTLabs/EvaporateJS

evaporate.js, example/evaporate_example.html
My server has a very robust authentication and verification process.  Every call to our server needs to be MD5 hashed and signed properly for authentication and verification to pass.  In order to do this I need to be able to set headers on the signer call and I need to be able to then hash and sign the entire signer request before it is sent to the server.  I have made three changes that should allow users to use more secure authentication and verification processes, such as HMAC, to authorize the signer request.
1) I added the 'signHeaders' property to add function options.  This property works like the 'signParams' property.  It takes an object of key/value pairs and uses those to set headers on the signer request.
2)  I enhanced both the 'signHeaders' and 'signParams' properties to …
=> Robust access to signer request

bower.json
Bower uses case sensitive search/install, and this package is registered
with the name "evaporatejs", not "EvaporateJS":
```
$ bower i --save EvaporateJS
bower                        ENOTFOUND Package EvaporateJS not found
$ bower i --save evaporatejs
...
bower evaporatejs#*            install evaporatejs#33acaf40e9
evaporatejs#33acaf40e9 vendor/assets/components/evaporatejs
```
=> Correct name in bower.json

README.md
Hi,
I'm not sure what's right place to put this blog post link, so just append it to the end of readme file.
You can change it as you need.
This pull request is a follow of https://github.com/TTLabs/EvaporateJS/issues/76.
We worked out a final solution for working with temporary credentials in Amazon EC2 instances and write a blog post about it, so want to share with you.
=> add a link to how to work with temporary credentials in Amazon EC2 instances blog post

evaporate.js
This prevents an InvalidStateError that is caused by setting the headers before xhr.open is called
=> set custom headers on signurl request after xhr is opened

README.md
I noticed some links that appeared to be intended to be markdown links, but were formatted incorrectly. This fixes them.
=> fix some readme links

README.md, evaporate.js, example/evaporate_example.html
Addresses #133 by asynchronously calling the `timeUrl` once at load time, calculating the offset from the current client time and then for each request, just offsetting the client time to reflect the associated server time.
Note: The logic assumes that the timeUrl fetch completes before the first file request is created. Whether this a good assumption, needs to be evaluated.
=> Removes synchronous timeUrl logic; fetches time once and uses an offset after that

README.md, evaporate.js
Candidate solution for Issue #136.
This PR uses the client reported file size to prevent the file from being added to EvaporateJS's file upload list. 
The proposed config option s `maxFileSize` where the default is no limit and the value is expressed in bytes as reported by JavaScript's `File` object.
=> Adds a configuration option to validate against a maximum file size.

evaporate.js
=> If no me.uploadId is set, don't send abort request

README.md, evaporate.js, example/evaporate_example_awsv4_signature.html, example/signing_example_awsv4_controller.rb
Addresses #157 . The `cryptoHmacMethod` option was not used. Also added sample Ruby on Rails code for a V4 controller generating the signing key.
=> ISSUE-157: Removes Superfluous Option + Adds Ruby Sample V4 Signing Controller

evaporate.js
The file object here has another file object with size property.
So we need to call `file.file.size` to actually get the size here otherwise it will return null
=> Fix maxFileSize check

evaporate.js
"".split will return [""] not [].  The knock on effect of this was
an = sign turning up in the payload, and therefore our computed hash
did not match Amazon's hash.
=> Fix bug causing SignatureDoesNotMatch errors. Closes #185.

evaporate.js
Works around this by parsing as HTML, not XML. Refer to #207 & #208.
=> Addresses XML incompatibilities for IE in DOM parsing

README.md, evaporate.js
For most regions other than 'us-east-1', the S3 endpoint must be correctly set. This pull request defaults the region to 'us-east-1' for backwards compatibility and correctly sets the default `aws_url`
for other regions.
The readme was updated to describe the applied logic.
For users who had to set aws_url explicitly might be able to use the new defaults.
Addresses #202.
=> Improves AWS Url Defaults for Regions other than us-east-1

evaporate.js
The first time a part failed did not reset the total bytes uploaded for the part. Addresses #209.
=> Resets the number of bytes uploaded earlier for when a part upload Fails

evaporate.js
`encodeURIComponent()` does not encode parentheses, but AWS do, and so we get
a signature mismatch.  This commit adds a manual conversion of
parentheses to their corresponding URL encodings.
=> Allow parentheses in filenames

README.md
This should be fixed in the TK rewrite. Closes #245 for now.
=> Attempts to clarify how the .add method can return an error message

evaporate.js, test/auth.spec.js, test/requests.spec.js, test/retry.spec.js
When creating the test coverage in #256, several unreproted issues were discovered. This PR adds coverage for them and applies the necessary fixes in advance of more refactoring to simplify the code and apply a Promise paradigm.
The issues are:
- the warn message regarding the partNumberMarker was not offset by 1, which it should be, to reference the correct part.
- if .start() was called on an aborted file, the aborted file was processed anyway, but should have been ignored.
- if a user tried to upload no files, then `complete` was never triggered.
- reported uploaded bytes doubled after resuming a partially uploaded file (the number of fully uploaded parts sizes were duplicated).
- reusing an uploaded S3 object should only have been abled if `computeConentMd5` is enabled.
- if the user …
=> Addresses Issues Identified When Creating Test Coverage

evaporate.js
As it stands, the localTimeOffset is applied by addition, resulting in the time slippage being doubled when sent in request header.
i) Consider Server time 15:19 and machine clock time 12:19, now - server_date  = -3 Then when applied 12:19 + (-3) = 09:19
ii) The Inverse also holds true, consider Server time 12:19 and machine clock time 15:19, now - server_date  = +3, When applied 15:19 + (+3) = 18:19
With this change both cases after applying the offset would give the server time.
=> Correctly calculate localTimeOffset

CHANGELOG.md, bower.json, evaporate.js, example/app.yaml, package.json
Addresses #276. Files weren't starting after a canceled file if the canceled file had not started and there was nothing left to upload when that file was canceled. The fix was to removed the non-started file from the queuedFiles list.
=> Addresses case where adding a file didn't start the file

README.md, evaporate.js
- Uses Uint8Array when dealing with ArrayBuffers since a plain old ArrayBuffer is deprecated.
- Optimizes the size of the last uploaded part to be no longer than what is required, not the entire part size
- Refactors how payloads are calculated and used
- Lazily calls getPayload for signing AWS Signature V4 requests
=> Enhancements and Improved Payload Calculation

example/app.yaml, example/evaporate_example.html
Defaults to V4 signing script as that the default AWS Sig Version of the library is V4. Also fixed loading of static assets.
=> Fix python example

README.md, evaporate.js, test/auth.spec.js, test/evaporate.spec.js
References #219, #293.
In order to allow developers to verify the string to sign, it's necessary to give access to the [canonical request](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html ).
This pull request attempts to provide the canonical request to the `signerUrl` and `customAuthMethod` options.
The canonical request is always passed to the `customAuthMethod` as the last argument; however to minimize unnecessary network load, this pr introduces a new option `sendCanonicalRequestToSignerUrl` (default: `false`). When this option is set, the canonical request will be sent as query parameter `canonical_request`.
This PR also optimizes the canonical request to only calculate it once per request and when retrying a request.
=> Enhances signerUrl and customAuthMethod to Include AWS V4 Canonical Request

README.md, evaporate.js, test/evaporate.spec.js
The callback is optional and is invoked as soon as the S3 multipart upload ID is determined. http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html
=> Adds new callback that delivers the S3 multipart upload ID

evaporate.js, test/aws_url.spec.js
With the refactoring in 2.0, it appears that the aws_url configuration option can be set on the `Evaporate#add`. Also attempts to use any builtin `URL` object to parse the url, falling back to `document` as a polyfill.
=> Allows AWS_URL to be set per file added

evaporate.js
The extend function used to replace Object.assign for #307 was not fully compatible with Object.assign, which prevented uploading files when localStorage was unavailable. Fixes #316
=> Fixes #316

README.md, evaporate.js, test/cached-parts.spec.js, test/evaporate.spec.js, test/s3-object-reuse.spec.js
For environments that do not support localStorage, this enhancement adds the option to mock localStorage using a plain old JavaScript object. Supports #319.
@YMIndustries what do you think?
=> Adds option to use local cache instead of localStorage

example/assets/example.css, example/evaporate_example.html
This branch implements a custom auth method in `example/evaporate_example.html` so that it's possible to (safely) test EvaporateJS when a secure signing method is not immediately unavailable.
=> Enhances evaporate_example.html to use a development-only customAuthMethod

evaporate.js
Now that Evaporate is being used in browser and browser-less environments, it makes sense to remove any unnecessary browser dependencies. This pull request removes all dependencies to  DOM parser as these dependencies are not thread safe and restrict compatibilities on web workers.
=> Removes dependence on a DOM parser for greater compatibility with browser-less environments

evaporate.js
When uploading with `computeContentMd5`, Evaporate was retaining memory. This pull request addresses that. Closes #335.
=> Addresses retained memory when uploading without md5Checksums

example/SigningExample.js
Fixes:
- envvars must be accessed through `process.env.<ENVVAR>`
- on most linux machines, the `env` utility is located at /usr/bin/env
Logging improvements:
- log when a server opens a connection on a port (otherwise I find myself wondering if the server process is running and where)
- log each request's method and url
- log the request payload and signature for url signer endpoint
cc @bikeath1337
=> Fix Node.js example + add logging

evaporate.js, test/auth.spec.js
Previously the PUT method was excluded. This may be the reason for some Micorosoft Edge compatibility.
Anyone able to give this branch a trial run? It works on Apple Version 60.0.3112.90 (Official Build) (64-bit). 
Might supersede #363
=> Applies the contentType to all signatures for all requests

evaporate.js
While working on a file upload for our app, noticed that error message was not very user friendly, e.g. "_File size too large. Maximum size allowed is 10485760_".
This little adjustment fixes that and makes it human readable:
_File size too large. Maximum size allowed is 10 MB_
=> Make maximum file size error message more human friendly

example/awsv4_signing_example.js
Hi,
first of all thank you for this great library!
I have been using your AWSv4 signing example for javascript and noticed that there is a tiny mistake in it which causes it to not work, so I created this PR to fix it.
=> Fixed broken example for signing awsv4 in js.

evaporate.js
`host` includes the port number (necessary for generating correct signatures when using S3 endpoints on non-standard ports) where `hostname` does not.
=> Use URL.host when generating headers to sign

evaporate.js
The `readableFileSize` method returned bit-based unit labels (kilobit, megabit, etc.), but `size` is measured in bytes. This change updates the units displayed to be consistent with the value used, which is in bytes.
Ref: https://github.com/TTLabs/EvaporateJS/issues/13
=> readableFileSize: correct units to bytes not bits
