- example/SigningExample.js
Hi TTLabs/videopixie, love the library. Helped me a lot.
Just added the node.js example.
Thanks.
> node exaample added

- README.md
> Update documentation for Evaporate timeURL

- evaporate.js
@SamPotts I looked at your PR and reduced it to its essence...I think.
> Handles case where a Blob’s last modified date can be null.

- evaporate.js
Adds support for checking if localStorage exists. Works off of @SamPotts grouped PR.
> Adds support for checking if localStorage exists

- evaporate.js
Cherry pick's @SamPotts commits.
> Adds signParams to the history cache so that the params are available on resume

- README.md
- evaporate.js
- example/evaporate_example_lambda.html
- example/signing_example_lambda.js
Its no longer necessary to run a server to do the signing requests, rather you can use the AWS Lambda service to host the function.
> Adds support to sign the request using amazon lambda

- evaporate.js
See https://github.com/TTLabs/EvaporateJS/issues/130
@SamPotts this is the remaining commit we need to vet.
> Fix for re-upload if ETag doesn't match

- README.md
- evaporate.js
This is an attempt to address #61 .
Note tha the documentation for ht .add() method appears to have been incorrect...I couldn't find where it got added but updated the docs to reflect what it does.
> ISSUE #61: Adds support for changing the config on the fly

- README.md
Addresses #158, corrects the documentation mistake added in 1.4.0.
> ISSUE-158: Corrects Readme regarding the .add() method

- evaporate.js
As mentioned in https://github.com/TTLabs/EvaporateJS/issues/168
> Fix for localStorage purging

- CHANGELOG.md
- README.md
- evaporate.js
> ISSUE #179: Enables setting xhr 'withCredentials' as part of the EvaporateJS configuration

- .gitignore
- .travis.yml
- package.json
- test/evaporate.spec.js
- test/mock/document.mock.js
I've put together the configuration and several very very basic tests for Evaporate as promised in #191. The test cases are something like a "bootstrap" of the whole testing thing. All branches of code need to be properly tested in all possible states.
This is work in progress, so I don't think it should be merged now. Let's talk about the tools and what everybody thinks about this. I'll try to add more tests when I have some time. Anyone, feel free to add some as well (probably via a PR to my branch `add-tests`).
I chose `ava` as a test runner, I've included `nyc` code coverage and also added config for Travis CI.
Sample output can be found [here](https://travis-ci.org/jakubzitny/EvaporateJS/builds/151413703).
The build is passing :)
[![Build …
> WIP: Add tests

- evaporate.js
Addresses #223.
This seems to fix the issue for me.
I've had one upload which still didn't finish, but that one seemed rather different, with a ton of errors in the network panel.
> Possible fixes for the retry_issue branch

- example/SigningExample-awsv4.js
- example/evaporate_example.html
Fixes example so with multiple uploads actions work on selected item rather than last.
Adds example of using AWS V4 auth. with Nodejs.
> Examples update

- evaporate.js
Resolves #227 , #223.
Fixes a bad log statement
Optimizes Monitor parts
Further simplifies processParts
Refines how counters are kept for uploads
Attempts to recognize when offline and adjusts monitoring interval to be more aggressive until back online, minimizing the wait to begin processing
Reduces frequency of monitorPartsInterval
Limits part submissions to avoid overloading browser async logic, causing chaotic connection errors.
Renames processFileParts to startFileProcessing
Cleans up logging a bit
Optimizes how total file progress is calculated, starting with the total file bytes uploaded and only adding on the parts in progress byte counts.
Applies numParts over s3Parts.length, where appropriate.
Optimizes processPartsListWithMd5Digests to only consider parts that need to be …
> Fixes known concurrency issues.

- README.md
- evaporate.js
- test/evaporate.spec.js
@jakubzitny hopefully this enhances your original work. Please review and note I added a spec for this.
> Provide the stringToSign to signResponseHandler

- README.md
- evaporate.js
- test/request_headers.spec.js
This PR rebases work by @jakubzitny and adds test coverage. Supersedes #232.
@jakubzitny please feel free to adapt the specs. I'm not really the up to speed on more elegant ways to reuse and write the expects.
> Adds xAmzHeadersAtCancel parameter to Evaporate#add

- evaporate.js
> Fall back to anchor tag if window.URL fails

- example/awsv4_signing_example.php
Attached an example PHP signing method I am using, it uses Laravel 5.3 functions, the concept is the same on all PHP platforms, this code could be used to show how to sign.
I tested the code with a project I am working, to works as excepted
> PHP Signature example

- example/SigningExample-awsv4.js
Fixes several small issues:
- Accessing envvars correctly (`process.env....` not `env....`)
- `env` utility is normally located at /usr/bin/env not /bin/env in the
shebang
Refactors
- Added setup and run instructions to comments at top of page
- Commented extensively throughout code
- Added super basic console logging for server start up and request
handling
- made js file executable
cc @bikeath1337
> (doc) Rewrite Node.js example code for AWS v4 signatures

- example/evaporate_example_awsv4_signature.html
- Adds missing event handler
- Addresses inconsistent whitespace
- Includes usage instructions
cc @bikeath1337
> Fix evaporate_example_awsv4_signature.html

- example/awsv4_signing_example.php
> awsv4_signing_example.php return plain text as response

- evaporate.js
Memory retention issues recurred with Chrome recently. I don't know why this happened as EvaporateJS code related to this did not change. I investigated the retention issue and was able to pin it down to passing the XMLHttpRequest object as a parameter to Promise.resolve.
> Addresses memory retention

- example/evaporate_example.html
> evaporate_example.html does not set awsRegion on create #453
